# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportEvents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportEvents
 pod 'DZNEmptyDataSet'
  target 'SportEventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportEventsUITests' do
    # Pods for testing
  end

end
